---
title: "Ejercicios Inter e Intravarianza"
author: "Mariana Castaño Garcia"
date: "2026-04-04"
lang: es
format: 
  html:
    theme: cosmo
    toc: true
    toc-depth: 2
    code-fold: false
execute:
  echo: true
  warning: false
  message: false
---

## 1. Datos

```{r}
mañana <- c(4.0, 3.5, 3.8, 3.6, 4.1)
tarde  <- c(3.8, 3.5, 3.0, 2.9)
noche  <- c(3.1, 2.5, 2.6)

datos <- c(mañana, tarde, noche)
datos
mañana 
tarde
noche

```

## 2. Tamaños y medias

```{r}
n1 <- length(mañana)
n2 <- length(tarde)
n3 <- length(noche)

media_total <- mean(datos)

m1 <- mean(mañana)
m2 <- mean(tarde)
m3 <- mean(noche)

mean(datos)
n1
n2
n3
m1
m2
m3
```

## 3. INTRAVARIANZA (σ²_W)

```{r}
var_w <- (var(mañana)*n1 +
          var(tarde)*n2 +
          var(noche)*n3) / length(datos)
var_w
```

Resultado: 0.1129167

## 4. INTERVARIANZA (σ²_B)

```{r}
var_b <- (n1*(m1 - media_total)^2 +
          n2*(m2 - media_total)^2 +
          n3*(m3 - media_total)^2) / length(datos)
var_b
```

Resultado: 0.18

## 5. Comprobación

```{r}
var_total <- var(datos)

var_w + var_b
var_total
```
